package br.com.oncast.acquirerpimp.bean.transaction.error;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;

@XmlType(name = "codigo")
@XmlEnum(Integer.class)
public enum CieloErrorType {

	@XmlEnumValue("1")
	INVALID_DATA_FORMAT,

	@XmlEnumValue("2")
	BAD_CREDENTIALS,

	@XmlEnumValue("3")
	INEXISTENT_TRANSACTION,

	@XmlEnumValue("10")
	NO_PERMISSION_TO_SEND_CREDIT_CARD,

	@XmlEnumValue("11")
	NO_PERMISSION_FOR_PAYMENT_TYPE,

	@XmlEnumValue("12")
	INVALID_NUMBER_OF_INSTALLMENTS,

	@XmlEnumValue("13")
	INVALID_AUTHORIZATION_TYPE_FOR_PAYMENT_TYPE,

	@XmlEnumValue("14")
	INVALID_DIRECT_AUTHORIZATION,

	@XmlEnumValue("15")
	MISSING_CREDIT_CARD_FOR_DIRECT_AUTHORIZATION,

	@XmlEnumValue("16")
	DUPLICATED_TID,

	@XmlEnumValue("17")
	MISSING_SECURITY_CODE,

	@XmlEnumValue("18")
	INVALID_SECURITY_CODE_INDICATOR,

	@XmlEnumValue("19")
	MISSING_RETURN_URL,

	@XmlEnumValue("20")
	CURRRENT_TRANSACTION_STATUS_DOES_NOT_ALLOW_AUTHORIZATION,

	@XmlEnumValue("21")
	AUTHORIZATION_PERIOD_EXPIRED,

	@XmlEnumValue("25")
	AUTHORIZATION_FAILED_BECAUSE_OF_AUTHENTICATION_RESULT,

	@XmlEnumValue("30")
	CURRRENT_TRANSACTION_STATUS_DOES_NOT_ALLOW_CAPTURE,

	@XmlEnumValue("31")
	CAPTURE_PERIOD_EXPIRED,

	@XmlEnumValue("32")
	INVALID_CAPTURE_VALUE,

	@XmlEnumValue("33")
	CAPTURE_FAILURE,

	@XmlEnumValue("34")
	MISSING_SHIPPING_CHARGES,

	@XmlEnumValue("35")
	INVALID_CREDIT_CARD_FLAG_FOR_SHIPPING_CHARGES,

	@XmlEnumValue("36")
	INVALID_PAYMENT_TYPE_FOR_SHIPPING_CHARGES,

	@XmlEnumValue("40")
	CANCELLATION_PERIOD_EXPIRED,

	@XmlEnumValue("41")
	CURRRENT_TRANSACTION_STATUS_DOES_NOT_ALLOW_CANCELLATION,

	@XmlEnumValue("42")
	CANCELLATION_FAILURE,

	@XmlEnumValue("43")
	CANCELLATION_VALUE_IS_GREATTER_THAN_AUTHORIZED_VALUE,

	@XmlEnumValue("51")
	INVALID_RECURRENCE,

	@XmlEnumValue("52")
	INVALID_OR_BLOCKED_TOKEN,

	@XmlEnumValue("53")
	NO_PERMISSION_FOR_RECURRENCE,

	@XmlEnumValue("54")
	INVALID_TOKEN_TRANSACTION,

	@XmlEnumValue("55")
	MISSING_CREDIT_CARD_NUMBER,

	@XmlEnumValue("56")
	MISSING_CREDIT_CARD_VALID_THU,

	@XmlEnumValue("57")
	TOKEN_GENERATION_FAILURE,

	@XmlEnumValue("61")
	INVALID_RECUURENCE_TRANSACTION,

	@XmlEnumValue("97")
	SERVICE_UNAVAILABLE,

	@XmlEnumValue("98")
	TIMEOUT,

	@XmlEnumValue("99")
	UNEXPECTED_FAILURE;

}
